Wrote a python script Using Gspread to automatically get data from Google Sheet.
Data-Epic/Omidiora_Emmanuel pull request #1
Opened 2023-10-22 13:26 UTC by olaemy

@elseagle
@AmazingGrace-D
@tobaadesugba

2023-10-24 23:21 UTC, elseagle requested changes
Thanks for the PR, kindly checkout the comments

2023-10-24 23:21 UTC, elseagle commented on README.md
We have some instructions on discord that could help make your readme better, kindly check #task-submissions

2023-10-24 23:21 UTC, elseagle commented on gspread_new.ipynb
Kindly move this to a python script, we can't review a jupyter-notebook

2023-10-30 07:31 UTC, elseagle commented on __pycache__/test_main.cpython-310-pytest-7.1.2.pyc
remove all files like this from your commits. you don't need `*.pyc` files, add it to your gitignore

2023-10-30 07:33 UTC, elseagle approved these changes
Please checkout the requested changes before you merge

2023-10-31 22:04 UTC, olaemy commented
Done, and commited all changes requested

2023-10-31 22:04 UTC, closed without merging